version: "3.9"

services:
  work:
    image: atcoder-rust:1.0.0
    build:
      context: docker
    working_dir: /work
    volumes:
      - .:/work:cached
      - target:/work/target
    tty: true

volumes:
  target:
